formatter: "markdown"
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
content: |-
  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Usage

  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```
